camera:
  - platform: synology
    url: !secret synology_url
    username: !secret synology_user
    password: !secret synology_password
    timeout: 15
    verify_ssl: False

binary_sensor:
  - platform: rest
    name: "CAMERA1 Motion Sensor"
    resource: !secret foscam_url
    device_class: motion
    scan_interval: 5
    value_template: >-
      {%- if "<motionDetectAlarm>2</motionDetectAlarm>" in value -%}
        {{ true }}
      {%- else -%}
        {{ false }}
      {%- endif -%}
